// Maps ISO 3166-1 alpha-2 lowercase country codes to the English category name
// used in the Wikimedia Commons "Climbing in <country>" categories.
// "The" prefix matters because Commons has e.g. "Climbing in the Czech Republic".
const COUNTRY_NAMES_EN: Record<string, string> = {
  ad: 'Andorra',
  ae: 'the United Arab Emirates',
  af: 'Afghanistan',
  al: 'Albania',
  am: 'Armenia',
  ar: 'Argentina',
  at: 'Austria',
  au: 'Australia',
  az: 'Azerbaijan',
  ba: 'Bosnia and Herzegovina',
  bd: 'Bangladesh',
  be: 'Belgium',
  bg: 'Bulgaria',
  bh: 'Bahrain',
  bo: 'Bolivia',
  br: 'Brazil',
  by: 'Belarus',
  ca: 'Canada',
  ch: 'Switzerland',
  cl: 'Chile',
  cn: 'China',
  co: 'Colombia',
  cr: 'Costa Rica',
  cu: 'Cuba',
  cy: 'Cyprus',
  cz: 'the Czech Republic',
  de: 'Germany',
  dk: 'Denmark',
  do: 'the Dominican Republic',
  dz: 'Algeria',
  ec: 'Ecuador',
  ee: 'Estonia',
  eg: 'Egypt',
  es: 'Spain',
  et: 'Ethiopia',
  fi: 'Finland',
  fo: 'the Faroe Islands',
  fr: 'France',
  gb: 'the United Kingdom',
  ge: 'Georgia',
  gr: 'Greece',
  hk: 'Hong Kong',
  hr: 'Croatia',
  hu: 'Hungary',
  id: 'Indonesia',
  ie: 'Ireland',
  il: 'Israel',
  in: 'India',
  iq: 'Iraq',
  ir: 'Iran',
  is: 'Iceland',
  it: 'Italy',
  jo: 'Jordan',
  jp: 'Japan',
  ke: 'Kenya',
  kg: 'Kyrgyzstan',
  kp: 'North Korea',
  kr: 'South Korea',
  kz: 'Kazakhstan',
  lb: 'Lebanon',
  li: 'Liechtenstein',
  lk: 'Sri Lanka',
  lt: 'Lithuania',
  lu: 'Luxembourg',
  lv: 'Latvia',
  ly: 'Libya',
  ma: 'Morocco',
  mc: 'Monaco',
  md: 'Moldova',
  me: 'Montenegro',
  mk: 'North Macedonia',
  mn: 'Mongolia',
  mt: 'Malta',
  mx: 'Mexico',
  my: 'Malaysia',
  na: 'Namibia',
  ng: 'Nigeria',
  nl: 'the Netherlands',
  no: 'Norway',
  np: 'Nepal',
  nz: 'New Zealand',
  om: 'Oman',
  pa: 'Panama',
  pe: 'Peru',
  ph: 'the Philippines',
  pk: 'Pakistan',
  pl: 'Poland',
  pt: 'Portugal',
  py: 'Paraguay',
  qa: 'Qatar',
  ro: 'Romania',
  rs: 'Serbia',
  ru: 'Russia',
  sa: 'Saudi Arabia',
  se: 'Sweden',
  sg: 'Singapore',
  si: 'Slovenia',
  sk: 'Slovakia',
  sy: 'Syria',
  th: 'Thailand',
  tn: 'Tunisia',
  tr: 'Turkey',
  tw: 'Taiwan',
  ua: 'Ukraine',
  us: 'the United States',
  uy: 'Uruguay',
  uz: 'Uzbekistan',
  ve: 'Venezuela',
  vn: 'Vietnam',
  ye: 'Yemen',
  za: 'South Africa',
  zw: 'Zimbabwe',
};

export const getCountryNameForCategory = (
  countryCode: string | undefined,
): string | null => {
  if (!countryCode) return null;
  return COUNTRY_NAMES_EN[countryCode.toLowerCase()] ?? null;
};
