/** Languages offered for OSM multilingual tags like `name:*` / `description:*`. */
export const TAG_LANGUAGES: Record<string, string> = {
  en: 'English',
  cs: 'Česky',
  sk: 'Slovenčina',
  de: 'Deutsch',
  pl: 'Polski',
  fr: 'Français',
  it: 'Italiano',
  es: 'Español',
  pt: 'Português',
  nl: 'Nederlands',
  uk: 'Українська',
  ru: 'Русский',
  hu: 'Magyar',
  ro: 'Română',
  bg: 'Български',
  el: 'Ελληνικά',
  hr: 'Hrvatski',
  sr: 'Српски',
  sl: 'Slovenščina',
  bs: 'Bosanski',
  sq: 'Shqip',
  mk: 'Македонски',
  et: 'Eesti',
  lv: 'Latviešu',
  lt: 'Lietuvių',
  fi: 'Suomi',
  sv: 'Svenska',
  da: 'Dansk',
  no: 'Norsk',
  nb: 'Norsk (bokmål)',
  nn: 'Norsk (nynorsk)',
  is: 'Íslenska',
  ga: 'Gaeilge',
  cy: 'Cymraeg',
  ca: 'Català',
  eu: 'Euskara',
  gl: 'Galego',
  mt: 'Malti',
  tr: 'Türkçe',
  be: 'Беларуская',
  lb: 'Lëtzebuergesch',
};

export const TAG_LANGUAGE_FLAGS: Record<string, string> = {
  en: '🇬🇧',
  cs: '🇨🇿',
  sk: '🇸🇰',
  de: '🇩🇪',
  pl: '🇵🇱',
  fr: '🇫🇷',
  it: '🇮🇹',
  es: '🇪🇸',
  pt: '🇵🇹',
  nl: '🇳🇱',
  uk: '🇺🇦',
  ru: '🇷🇺',
  hu: '🇭🇺',
  ro: '🇷🇴',
  bg: '🇧🇬',
  el: '🇬🇷',
  hr: '🇭🇷',
  sr: '🇷🇸',
  sl: '🇸🇮',
  bs: '🇧🇦',
  sq: '🇦🇱',
  mk: '🇲🇰',
  et: '🇪🇪',
  lv: '🇱🇻',
  lt: '🇱🇹',
  fi: '🇫🇮',
  sv: '🇸🇪',
  da: '🇩🇰',
  no: '🇳🇴',
  nb: '🇳🇴',
  nn: '🇳🇴',
  is: '🇮🇸',
  ga: '🇮🇪',
  cy: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  ca: '🇦🇩',
  eu: '🇪🇸',
  gl: '🇪🇸',
  mt: '🇲🇹',
  tr: '🇹🇷',
  be: '🇧🇾',
  lb: '🇱🇺',
};
